services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=chesspectationsdb'
      - 'POSTGRES_PASSWORD=password1'
      - 'POSTGRES_USER=postgres'
    ports:
      - '59760:5432'
